### ISSUE TITLE
Fail to find size of message (and generally have issues parsing email messages)

### ISSUE THREAD

**Issue by scanner** [scanner/asimap#282]
Python's mail generator support can have trouble parsing messages we get from the internet. Nasty internet.

https://apricot-systematic.sentry.io/issues/5581665705/?alert_rule_id=14797875&alert_timestamp=1720374270795&alert_type=email&environment=devel&notification_uuid=6c6abf36-0920-46dd-86ff-2dfd9545342a&project=4506221189267456&referrer=alert_email

```python
Traceback (most recent call last):
  File "/app/asimap/user_server.py", line 229, in start
    await self.cmd_processor.command(imap_cmd)
  File "/app/asimap/client.py", line 156, in command
    result = await getattr(self, f"do_{imap_command.command}")(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/client.py", line 1088, in do_fetch
    async for idx, results in self.mbox.fetch(
  File "/app/asimap/mbox.py", line 2203, in fetch
    iter_results.append(await elt.fetch(ctx))
                        ^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/fetch.py", line 187, in fetch
    msg = await self.ctx.email_message()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/search.py", line 191, in email_message
    message_from_string(msg_as_string(await self.msg()), policy=SMTP),
                                      ^^^^^^^^^^^^^^^^
  File "/app/asimap/search.py", line 148, in msg
    self._msg = await self.mailbox.get_and_cache_msg(self.msg_key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/mbox.py", line 1696, in get_and_cache_msg
    self.server.msg_cache.add(self.name, msg_key, msg)
  File "/app/asimap/message_cache.py", line 197, in add
    msg_size = get_msg_size(msg)
               ^^^^^^^^^^^^^^^^^
  File "/app/asimap/generator.py", line 269, in get_msg_size
    msg_str = msg_as_string(msg, headers=headers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/generator.py", line 250, in msg_as_string
    return _msg_as_string(msg, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/generator.py", line 239, in _msg_as_string
    g.flatten(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 115, in flatten
    self._write(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 198, in _write
    self._write_headers(msg)
  File "/app/asimap/generator.py", line 67, in _write_headers
    super()._write_headers(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 225, in _write_headers
    self.write(self.policy.fold(h, v))
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/policy.py", line 184, in fold
    return self._fold(name, value, refold_binary=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/policy.py", line 221, in _fold
    return self.header_factory(name, ''.join(lines)).fold(policy=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/headerregistry.py", line 253, in fold
    return header.fold(policy=policy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/_header_value_parser.py", line 156, in fold
    return _refold_parse_tree(self, policy=policy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/_header_value_parser.py", line 2858, in _refold_parse_tree
    last_ew = _fold_as_ew(tstr, lines, maxlen, last_ew,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/_header_value_parser.py", line 2981, in _fold_as_ew
    encoded_word = _ew.encode(to_encode_word, charset=encode_as)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/_encoded_words.py", line 222, in encode
    bstring = string.encode('ascii', 'surrogateescape')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

Need to find a way to handle these without having to re-invent the tree too much.

**Comment by scanner** [comment]
Fixed in PR GH-284
