### ISSUE TITLE
ERROR:user_server.start: Exception in <asimap.user_server.IMAPClientProxy object at 0x7f75443d9fa0>: 'Group' object has no attribute 'local_part'

### ISSUE THREAD

**Issue by scanner** [scanner/asimap#285]
another problem parsing an email message:

```python
Traceback (most recent call last):
  File "/app/asimap/user_server.py", line 229, in start
    await self.cmd_processor.command(imap_cmd)
  File "/app/asimap/client.py", line 156, in command
    result = await getattr(self, f"do_{imap_command.command}")(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/client.py", line 1088, in do_fetch
    async for idx, results in self.mbox.fetch(
  File "/app/asimap/mbox.py", line 2203, in fetch
    iter_results.append(await elt.fetch(ctx))
                        ^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/fetch.py", line 187, in fetch
    msg = await self.ctx.email_message()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/search.py", line 191, in email_message
    message_from_string(msg_as_string(await self.msg()), policy=SMTP),
                                      ^^^^^^^^^^^^^^^^
  File "/app/asimap/search.py", line 148, in msg
    self._msg = await self.mailbox.get_and_cache_msg(self.msg_key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/mbox.py", line 1696, in get_and_cache_msg
    self.server.msg_cache.add(self.name, msg_key, msg)
  File "/app/asimap/message_cache.py", line 193, in add
    msg_size = get_msg_size(msg)
               ^^^^^^^^^^^^^^^^^
  File "/app/asimap/generator.py", line 269, in get_msg_size
    msg_str = msg_as_string(msg, headers=headers)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/generator.py", line 250, in msg_as_string
    return _msg_as_string(msg, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/generator.py", line 239, in _msg_as_string
    g.flatten(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 115, in flatten
    self._write(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 198, in _write
    self._write_headers(msg)
  File "/app/asimap/generator.py", line 67, in _write_headers
    super()._write_headers(msg)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/generator.py", line 225, in _write_headers
    self.write(self.policy.fold(h, v))
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/policy.py", line 184, in fold
    return self._fold(name, value, refold_binary=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/policy.py", line 221, in _fold
    return self.header_factory(name, ''.join(lines)).fold(policy=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/headerregistry.py", line 604, in __call__
    return self[name](name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/headerregistry.py", line 192, in __new__
    cls.parse(value, kwds)
  File "/usr/local/lib/python3.12/email/headerregistry.py", line 347, in parse
    mb.local_part or '',
    ^^^^^^^^^^^^^
AttributeError: 'Group' object has no attribute 'local_part'
```

**Comment by scanner** [comment]
Also see: https://apricot-systematic.sentry.io/issues/5582125255/?project=4506221189267456&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=8

**Comment by scanner** [comment]
The email message was totally malformed. While we should have a way to quarantine bad messages for now I just fixed the base email message.
