### ISSUE TITLE
Looks like we are hitting a case where a message has no uid.. was it inserted in the middle of operation?

### ISSUE THREAD

**Issue by scanner** [scanner/asimap#298]
```python
Traceback (most recent call last):
  File "/app/asimap/user_server.py", line 235, in start
    await self.cmd_processor.command(imap_cmd)
  File "/app/asimap/client.py", line 156, in command
    result = await getattr(self, f"do_{imap_command.command}")(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/asimap/client.py", line 1088, in do_fetch
    async for idx, results in self.mbox.fetch(
  File "/app/asimap/mbox.py", line 2121, in fetch
    assert uid_max  # XXX If this is None should we force a resync?
           ^^^^^^^
AssertionError
```

See: https://apricot-systematic.sentry.io/issues/5592430686/?alert_rule_id=14797875&alert_timestamp=1720635354796&alert_type=email&environment=devel&notification_uuid=c067b53d-2194-4214-adb3-5302051133a6&project=4506221189267456&referrer=alert_email

**Comment by scanner** [comment]
GH-306 fixes this
